version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - SYMFONY_ENV=dev
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/app.ini:ro
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fitmatch?serverVersion=14&charset=utf8

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fitmatch
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: